#!/bin/bash

echo "🚀 Configurando Vercel - URL Correta: www.insightfy.com.br"
echo "================================================================"
echo ""

# Variáveis corretas
APP_ID="3361128087359379"
APP_SECRET="7e6216e859be7639fa4de061536ce944"
REDIRECT_URI="https://www.insightfy.com.br/meta-ads-config"
APP_URL="https://www.insightfy.com.br"

echo "📝 Adicione estas variáveis MANUALMENTE no Dashboard da Vercel:"
echo ""
echo "🔗 Acesse: https://vercel.com/mafcos-projects/metri-com-flow/settings/environment-variables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  VITE_META_APP_ID"
echo "    Valor: $APP_ID"
echo "    Ambiente: Production"
echo ""
echo "2️⃣  VITE_META_APP_SECRET"
echo "    Valor: $APP_SECRET"
echo "    Ambiente: Production"
echo ""
echo "3️⃣  VITE_META_REDIRECT_URI"
echo "    Valor: $REDIRECT_URI"
echo "    Ambiente: Production"
echo ""
echo "4️⃣  VITE_APP_URL"
echo "    Valor: $APP_URL"
echo "    Ambiente: Production"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Instruções:"
echo ""
echo "   1. Abra o link acima no navegador"
echo "   2. Para cada variável:"
echo "      - Se já existir: clique nos 3 pontinhos > Edit > cole o novo valor"
echo "      - Se não existir: clique 'Add New' > cole nome e valor"
echo "   3. Sempre marque 'Production'"
echo "   4. Clique 'Save'"
echo ""
echo "   5. Depois de adicionar todas, faça redeploy:"
echo "      - Vá em 'Deployments'"
echo "      - Clique no último deploy > 'Redeploy'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  LEMBRETE: Você também precisa atualizar o Meta for Developers!"
echo ""
echo "   URI CORRETA para adicionar no Meta:"
echo "   ✅ https://www.insightfy.com.br/meta-ads-config"
echo ""
echo "   Link: https://developers.facebook.com/apps/3361128087359379"
echo "   Local: Produtos > Login do Facebook para Empresas > Configurações"
echo ""
echo "================================================================"
