-- Ensure subscription payments table tracks Stripe metadata for history sync

ALTER TABLE public.subscription_payments
  ADD COLUMN IF NOT EXISTS stripe_payment_intent_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_invoice_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_hosted_invoice_url TEXT,
  ADD COLUMN IF NOT EXISTS stripe_receipt_url TEXT;

COMMENT ON COLUMN public.subscription_payments.stripe_payment_intent_id IS 'Payment intent id generated by Stripe';
COMMENT ON COLUMN public.subscription_payments.stripe_invoice_id IS 'Stripe invoice id for the payment record';
COMMENT ON COLUMN public.subscription_payments.stripe_hosted_invoice_url IS 'URL to the hosted invoice page on Stripe';
COMMENT ON COLUMN public.subscription_payments.stripe_receipt_url IS 'Direct receipt or PDF URL provided by Stripe';

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_payments_unique_stripe_invoice
  ON public.subscription_payments(stripe_invoice_id)
  WHERE stripe_invoice_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_subscription_payments_stripe_sync_lookup
  ON public.subscription_payments(subscription_id, stripe_invoice_id)
  WHERE stripe_invoice_id IS NOT NULL;

COMMENT ON TABLE public.subscription_payments
  IS 'Individual payment records for organization subscriptions with Stripe metadata';
